import type {
  Account,
  Alert,
  CreditFacility,
  Incident,
  Operator,
  Payment,
  RemoteNode,
} from "./types";

export const DEMO_OPERATORS: Operator[] = [
  {
    id: "BV-OPS-01",
    name: "Mara Voss",
    role: "Command lead",
    seat: "Jersey City · Deck A",
    shift: "alpha",
    status: "on-desk",
    region: "EWR",
  },
  {
    id: "BV-OPS-07",
    name: "Julian Peck",
    role: "Rails officer",
    seat: "Remote · Austin",
    shift: "alpha",
    status: "remote",
    region: "AUS",
  },
  {
    id: "BV-OPS-12",
    name: "Nia Okonkwo",
    role: "Risk sentinel",
    seat: "Jersey City · Deck C",
    shift: "alpha",
    status: "on-desk",
    region: "EWR",
  },
  {
    id: "BV-OPS-19",
    name: "Eli Navarro",
    role: "Treasury",
    seat: "Remote · Denver",
    shift: "bravo",
    status: "remote",
    region: "DEN",
  },
  {
    id: "BV-OPS-22",
    name: "Priya Shah",
    role: "Credit desk",
    seat: "Remote · Chicago",
    shift: "night",
    status: "offline",
    region: "ORD",
  },
  {
    id: "BV-OPS-31",
    name: "Jonah Hale",
    role: "Node wrangler",
    seat: "Jersey City · NOC",
    shift: "alpha",
    status: "on-desk",
    region: "EWR",
  },
];

export const DEMO_KEY = "coexist";

export const ACCOUNTS: Account[] = [
  {
    id: "BV-881204",
    legal: "Harbor & Pine Provisions LLC",
    dba: "Harbor & Pine",
    city: "Portland",
    state: "OR",
    deposits: 2_480_000,
    apyPlan: "Premier",
    status: "active",
    risk: 12,
    naics: "Food wholesale",
  },
  {
    id: "BV-190443",
    legal: "Northline Fabrication Inc",
    dba: "Northline",
    city: "Cleveland",
    state: "OH",
    deposits: 6_120_500,
    apyPlan: "Plus",
    status: "review",
    risk: 41,
    naics: "Metal fabrication",
  },
  {
    id: "BV-552910",
    legal: "Solstice Dental Group PA",
    dba: "Solstice Dental",
    city: "Tampa",
    state: "FL",
    deposits: 890_220,
    apyPlan: "Standard",
    status: "active",
    risk: 8,
    naics: "Healthcare",
  },
  {
    id: "BV-774001",
    legal: "Kite & Lantern Media LLC",
    dba: "Kite + Lantern",
    city: "Brooklyn",
    state: "NY",
    deposits: 412_880,
    apyPlan: "Plus",
    status: "frozen",
    risk: 78,
    naics: "Advertising",
  },
  {
    id: "BV-330128",
    legal: "Red Mesa Logistics Co",
    dba: "Red Mesa",
    city: "Albuquerque",
    state: "NM",
    deposits: 3_904_100,
    apyPlan: "Premier",
    status: "active",
    risk: 22,
    naics: "Trucking",
  },
  {
    id: "BV-901773",
    legal: "Lumen Circuit Labs Inc",
    dba: "Lumen Circuit",
    city: "Austin",
    state: "TX",
    deposits: 11_250_000,
    apyPlan: "Premier",
    status: "active",
    risk: 17,
    naics: "Electronics",
  },
  {
    id: "BV-448291",
    legal: "Glasshouse Botanicals LLC",
    dba: "Glasshouse",
    city: "Sacramento",
    state: "CA",
    deposits: 1_105_440,
    apyPlan: "Standard",
    status: "active",
    risk: 14,
    naics: "Agriculture",
  },
  {
    id: "BV-612004",
    legal: "Ironroot Construction LLC",
    dba: "Ironroot",
    city: "Charlotte",
    state: "NC",
    deposits: 5_330_090,
    apyPlan: "Plus",
    status: "review",
    risk: 53,
    naics: "Construction",
  },
];

const now = Date.now();

export const PAYMENTS: Payment[] = [
  {
    id: "ACH-940221",
    kind: "ACH",
    amount: 184_500,
    from: "Harbor & Pine",
    to: "Cascade Cold Storage",
    accountId: "BV-881204",
    status: "queued",
    submittedAt: now - 4 * 60_000,
    memo: "Weekly produce settlement",
    rail: "ACH credit · same-day",
  },
  {
    id: "WIR-118304",
    kind: "WIRE",
    amount: 2_250_000,
    from: "Lumen Circuit",
    to: "Kyoto Precision KK",
    accountId: "BV-901773",
    status: "held",
    submittedAt: now - 18 * 60_000,
    memo: "Q3 tooling · OFAC check",
    rail: "Fedwire · international",
  },
  {
    id: "RTP-772910",
    kind: "RTP",
    amount: 42_880,
    from: "Red Mesa",
    to: "Diesel Direct West",
    accountId: "BV-330128",
    status: "queued",
    submittedAt: now - 90_000,
    memo: "Fuel float",
    rail: "RTP · instant",
  },
  {
    id: "CHK-33019",
    kind: "CHECK",
    amount: 9_740,
    from: "Solstice Dental",
    to: "Patterson Dental Supply",
    accountId: "BV-552910",
    status: "queued",
    submittedAt: now - 52 * 60_000,
    memo: "Remote deposit · batch 12",
    rail: "Check · RDC",
  },
  {
    id: "ACH-940188",
    kind: "ACH",
    amount: 61_200,
    from: "Northline",
    to: "AK Steel Service",
    accountId: "BV-190443",
    status: "held",
    submittedAt: now - 26 * 60_000,
    memo: "Unusual velocity vs baseline",
    rail: "ACH debit · next-day",
  },
  {
    id: "WIR-118199",
    kind: "WIRE",
    amount: 475_000,
    from: "Ironroot",
    to: "Piedmont Title Escrow",
    accountId: "BV-612004",
    status: "queued",
    submittedAt: now - 8 * 60_000,
    memo: "Lot 14 close",
    rail: "Fedwire · domestic",
  },
  {
    id: "ACH-939901",
    kind: "ACH",
    amount: 12_400,
    from: "Kite + Lantern",
    to: "Meta Ads",
    accountId: "BV-774001",
    status: "rejected",
    submittedAt: now - 3 * 3600_000,
    memo: "Account frozen · media spend",
    rail: "ACH debit",
  },
  {
    id: "RTP-772844",
    kind: "RTP",
    amount: 8_250,
    from: "Glasshouse",
    to: "Pacific Growers Co-op",
    accountId: "BV-448291",
    status: "settled",
    submittedAt: now - 2 * 3600_000,
    memo: "Seed stock",
    rail: "RTP · instant",
  },
];

export const CREDITS: CreditFacility[] = [
  {
    id: "LOC-20441",
    accountId: "BV-901773",
    legal: "Lumen Circuit Labs Inc",
    kind: "line",
    limit: 250_000,
    drawn: 142_800,
    rate: 11.4,
    status: "performing",
  },
  {
    id: "LOC-19802",
    accountId: "BV-330128",
    legal: "Red Mesa Logistics Co",
    kind: "line",
    limit: 175_000,
    drawn: 168_200,
    rate: 12.1,
    status: "watch",
  },
  {
    id: "TLN-44190",
    accountId: "BV-612004",
    legal: "Ironroot Construction LLC",
    kind: "term",
    limit: 500_000,
    drawn: 412_000,
    rate: 10.8,
    status: "performing",
  },
  {
    id: "LOC-17660",
    accountId: "BV-190443",
    legal: "Northline Fabrication Inc",
    kind: "line",
    limit: 120_000,
    drawn: 96_400,
    rate: 13.2,
    status: "past-due",
  },
  {
    id: "LOC-22108",
    accountId: "BV-881204",
    legal: "Harbor & Pine Provisions LLC",
    kind: "line",
    limit: 80_000,
    drawn: 18_250,
    rate: 11.9,
    status: "performing",
  },
];

export const ALERTS: Alert[] = [
  {
    id: "RSK-441",
    severity: "critical",
    title: "Outbound wire held · OFAC dual control",
    detail: "WIR-118304 to Kyoto Precision KK requires a second officer.",
    accountId: "BV-901773",
    createdAt: now - 18 * 60_000,
    acked: false,
  },
  {
    id: "RSK-438",
    severity: "watch",
    title: "ACH velocity breach",
    detail: "Northline Fabrication 3.4× 30-day ACH debit baseline.",
    accountId: "BV-190443",
    createdAt: now - 26 * 60_000,
    acked: false,
  },
  {
    id: "RSK-429",
    severity: "critical",
    title: "Account frozen · mule pattern",
    detail: "Kite & Lantern inbound/outbound pairing matches typology T-19.",
    accountId: "BV-774001",
    createdAt: now - 3 * 3600_000,
    acked: true,
  },
  {
    id: "RSK-422",
    severity: "info",
    title: "New device on Premier account",
    detail: "Lumen Circuit · macOS 15 from Austin, known office ASN.",
    accountId: "BV-901773",
    createdAt: now - 55 * 60_000,
    acked: false,
  },
  {
    id: "RSK-418",
    severity: "watch",
    title: "Line of credit 96% utilized",
    detail: "Red Mesa Logistics approaching hard cap; auto-decline risk.",
    accountId: "BV-330128",
    createdAt: now - 2 * 3600_000,
    acked: false,
  },
];

export const INCIDENTS: Incident[] = [
  {
    id: "INC-2044",
    title: "Fedwire dual-control backlog",
    severity: "watch",
    status: "open",
    owner: "Julian Peck",
    openedAt: now - 22 * 60_000,
    notes: "Two international wires waiting on second officer. Desk alpha short one.",
  },
  {
    id: "INC-2039",
    title: "Edge node DEN-2 packet loss",
    severity: "watch",
    status: "acked",
    owner: "Jonah Hale",
    openedAt: now - 3 * 3600_000,
    notes: "Degraded path via DEN; traffic shifted to ORD. Carrier ticket opened.",
  },
  {
    id: "INC-2031",
    title: "RDC image quality spike",
    severity: "info",
    status: "resolved",
    owner: "Nia Okonkwo",
    openedAt: now - 26 * 3600_000,
    notes: "Mobile capture model rolled back. Settled.",
  },
];

export const NODES: RemoteNode[] = [
  {
    id: "EWR-HQ",
    name: "Jersey City HQ",
    kind: "hq",
    city: "Jersey City",
    lat: 40.73,
    lon: -74.07,
    status: "online",
    latencyMs: 8,
    cpu: 41,
    sessions: 18,
  },
  {
    id: "IAD-CORE",
    name: "Virginia core",
    kind: "cloud",
    city: "Ashburn",
    lat: 39.04,
    lon: -77.49,
    status: "online",
    latencyMs: 14,
    cpu: 62,
    sessions: 44,
  },
  {
    id: "ORD-CORE",
    name: "Chicago core",
    kind: "cloud",
    city: "Chicago",
    lat: 41.88,
    lon: -87.63,
    status: "online",
    latencyMs: 22,
    cpu: 55,
    sessions: 31,
  },
  {
    id: "DEN-EDGE",
    name: "Denver edge",
    kind: "edge",
    city: "Denver",
    lat: 39.74,
    lon: -104.99,
    status: "degraded",
    latencyMs: 86,
    cpu: 71,
    sessions: 9,
  },
  {
    id: "DFW-EDGE",
    name: "Dallas edge",
    kind: "edge",
    city: "Dallas",
    lat: 32.78,
    lon: -96.8,
    status: "online",
    latencyMs: 28,
    cpu: 38,
    sessions: 12,
  },
  {
    id: "SJC-EDGE",
    name: "San Jose edge",
    kind: "edge",
    city: "San Jose",
    lat: 37.34,
    lon: -121.89,
    status: "online",
    latencyMs: 41,
    cpu: 33,
    sessions: 16,
  },
  {
    id: "CCB-PARTNER",
    name: "Coastal Community Bank",
    kind: "partner",
    city: "Everett",
    lat: 47.98,
    lon: -122.2,
    status: "online",
    latencyMs: 52,
    cpu: 24,
    sessions: 4,
  },
  {
    id: "STRIPE-RAIL",
    name: "Stripe payments rail",
    kind: "partner",
    city: "South San Francisco",
    lat: 37.65,
    lon: -122.41,
    status: "online",
    latencyMs: 36,
    cpu: 48,
    sessions: 7,
  },
];

export const TREASURY_SERIES = [2.04, 2.07, 2.09, 2.11, 2.14, 2.16, 2.18, 2.19, 2.2, 2.21, 2.2, 2.22];
export const ACH_SERIES = [118, 142, 131, 166, 154, 171, 188, 176, 194, 201, 186, 212];
export const RISK_SERIES = [12, 14, 11, 18, 22, 19, 16, 21, 28, 24, 26, 23];
